In [1]:
import numpy as np
import pandas as pd

In [16]:
bond_prices = np.random.uniform(95, 105, size = (100,))
bond_prices

array([ 98.80079051, 104.42348546, 103.31892213,  98.2037781 ,
       102.54586615,  98.23811484, 103.20822182, 102.61413791,
       104.75909526,  96.17893185, 104.97489147, 103.13116913,
        98.26466   ,  95.60383504, 101.40670942, 102.47972984,
        97.36352989, 101.45785741, 101.80789155,  98.00601157,
       102.4214705 ,  98.74677544,  99.45440886, 100.5390276 ,
       103.62918178, 100.41778216, 102.12071717, 100.96410006,
        96.29518831, 101.37445135, 102.41827682,  96.64880008,
        96.72166764, 102.56183117, 103.348281  ,  99.36355713,
       104.92079269, 103.95943751,  98.56312671,  98.38593763,
        97.57659265, 103.25184342,  97.58396861, 103.07907003,
       102.80269881,  99.21022101,  98.25774257, 101.33365874,
        99.76759619,  97.05539623, 104.2282368 ,  95.11284331,
        99.08350074,  99.83220006, 102.92427126, 103.34553583,
        97.23246321,  95.3984885 , 104.28090918,  99.5880473 ,
       103.40139361, 101.46950939, 101.16292145, 102.12

In [17]:
coupon_rates = np.random.uniform(2.5, 5.5, size = (100,))
coupon_rates

array([4.69702766, 4.24459395, 3.91820121, 5.11394714, 4.72939442,
       4.6621585 , 3.2865801 , 2.62053963, 3.01279419, 3.4522313 ,
       2.71592653, 4.92473693, 4.31688202, 5.10869693, 5.30612826,
       2.88024131, 4.34813347, 3.60127122, 3.69477166, 3.22399106,
       3.07844846, 3.08143288, 2.52249609, 2.76958433, 4.53916164,
       4.54609884, 5.47880293, 3.03863311, 3.45947485, 2.75489267,
       3.41037538, 4.56053815, 2.61782257, 3.44937854, 2.88270878,
       4.35966328, 2.77158101, 4.32669342, 2.70329333, 3.01947014,
       3.39906039, 4.51192978, 3.9421754 , 3.6549651 , 4.3004172 ,
       3.10227818, 4.47686063, 4.53373654, 2.83216382, 4.31748349,
       2.92779265, 3.58129896, 3.34881488, 3.66105713, 4.81125805,
       4.90048043, 4.66008027, 4.63120428, 4.18698533, 3.41769067,
       5.17112076, 5.21002196, 2.77741437, 5.00261398, 5.22588741,
       4.00455866, 3.65882716, 2.56009907, 5.05745568, 3.18102007,
       5.2819627 , 3.01894742, 3.83363847, 3.90894776, 4.93493

In [18]:
face_values = np.array([100.0] * 100)
face_values

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100.])

In [19]:
countries = sorted(["ARG", "AUS", "US", "IND", "UK", "CAN", "JPN", "NZ", "GMNY", "RSA"])
countries

['ARG', 'AUS', 'CAN', 'GMNY', 'IND', 'JPN', 'NZ', 'RSA', 'UK', 'US']

In [20]:
time_ranges = np.arange(0.5, 10.5, 0.5)
time_ranges

array([ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,
        6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [21]:
country_times = dict()
for country in countries:
    country_times[country] = np.random.choice(time_ranges, 10, replace = False)
country_times

{'ARG': array([6. , 4. , 5. , 5.5, 8.5, 4.5, 1.5, 2.5, 6.5, 2. ]),
 'AUS': array([7.5, 7. , 9.5, 8. , 2.5, 3. , 9. , 6.5, 4.5, 6. ]),
 'CAN': array([5.5, 4.5, 4. , 2.5, 8. , 5. , 6. , 9.5, 3.5, 3. ]),
 'GMNY': array([3.5, 6. , 4.5, 9. , 4. , 2.5, 5.5, 8. , 9.5, 5. ]),
 'IND': array([ 5.5,  0.5,  8. , 10. ,  9. ,  7. ,  7.5,  2. ,  4.5,  3.5]),
 'JPN': array([ 7. ,  4. ,  5. , 10. ,  1. ,  3.5,  1.5,  4.5,  9. ,  7.5]),
 'NZ': array([10. ,  4. ,  5. ,  3.5,  2.5,  8.5,  9.5,  9. ,  5.5,  2. ]),
 'RSA': array([ 2. ,  7.5,  3.5,  4.5,  8.5,  9.5,  0.5, 10. ,  6. ,  1.5]),
 'UK': array([4. , 9. , 9.5, 8.5, 3.5, 2. , 5.5, 6.5, 1. , 7.5]),
 'US': array([6. , 7. , 1. , 1.5, 5. , 9.5, 4.5, 8. , 9. , 4. ])}

In [22]:
asset_id = list()
for country in country_times:
    for year in country_times[country]:
        asset_id.append(country + " " + str(year) + "Y")

print(asset_id)

['ARG 6.0Y', 'ARG 4.0Y', 'ARG 5.0Y', 'ARG 5.5Y', 'ARG 8.5Y', 'ARG 4.5Y', 'ARG 1.5Y', 'ARG 2.5Y', 'ARG 6.5Y', 'ARG 2.0Y', 'AUS 7.5Y', 'AUS 7.0Y', 'AUS 9.5Y', 'AUS 8.0Y', 'AUS 2.5Y', 'AUS 3.0Y', 'AUS 9.0Y', 'AUS 6.5Y', 'AUS 4.5Y', 'AUS 6.0Y', 'CAN 5.5Y', 'CAN 4.5Y', 'CAN 4.0Y', 'CAN 2.5Y', 'CAN 8.0Y', 'CAN 5.0Y', 'CAN 6.0Y', 'CAN 9.5Y', 'CAN 3.5Y', 'CAN 3.0Y', 'GMNY 3.5Y', 'GMNY 6.0Y', 'GMNY 4.5Y', 'GMNY 9.0Y', 'GMNY 4.0Y', 'GMNY 2.5Y', 'GMNY 5.5Y', 'GMNY 8.0Y', 'GMNY 9.5Y', 'GMNY 5.0Y', 'IND 5.5Y', 'IND 0.5Y', 'IND 8.0Y', 'IND 10.0Y', 'IND 9.0Y', 'IND 7.0Y', 'IND 7.5Y', 'IND 2.0Y', 'IND 4.5Y', 'IND 3.5Y', 'JPN 7.0Y', 'JPN 4.0Y', 'JPN 5.0Y', 'JPN 10.0Y', 'JPN 1.0Y', 'JPN 3.5Y', 'JPN 1.5Y', 'JPN 4.5Y', 'JPN 9.0Y', 'JPN 7.5Y', 'NZ 10.0Y', 'NZ 4.0Y', 'NZ 5.0Y', 'NZ 3.5Y', 'NZ 2.5Y', 'NZ 8.5Y', 'NZ 9.5Y', 'NZ 9.0Y', 'NZ 5.5Y', 'NZ 2.0Y', 'RSA 2.0Y', 'RSA 7.5Y', 'RSA 3.5Y', 'RSA 4.5Y', 'RSA 8.5Y', 'RSA 9.5Y', 'RSA 0.5Y', 'RSA 10.0Y', 'RSA 6.0Y', 'RSA 1.5Y', 'UK 4.0Y', 'UK 9.0Y', 'UK 9.5Y', 'U

In [23]:
len(set(asset_id))

100

In [24]:
time_periods = list()
for country in country_times:
    for year in country_times[country]:
        time_periods.append(year)

In [25]:
df_dict = {
    "asset_id" : asset_id,
    "bond_price" : bond_prices,
    "coupon_rate" : coupon_rates,
    "face_value" : face_values,
    "time_period" : time_periods
}

In [26]:
bond_data = pd.DataFrame(df_dict)

In [27]:
bond_data.head()

asset_id  bond_price  coupon_rate  face_value  time_period
0  ARG 6.0Y   98.800791     4.697028       100.0          6.0
1  ARG 4.0Y  104.423485     4.244594       100.0          4.0
2  ARG 5.0Y  103.318922     3.918201       100.0          5.0
3  ARG 5.5Y   98.203778     5.113947       100.0          5.5
4  ARG 8.5Y  102.545866     4.729394       100.0          8.5

In [28]:
bond_data['bond_price'] = bond_data['bond_price'].round(3)
bond_data['coupon_rate'] = bond_data['coupon_rate'].round(3)
bond_data.head()

asset_id  bond_price  coupon_rate  face_value  time_period
0  ARG 6.0Y      98.801        4.697       100.0          6.0
1  ARG 4.0Y     104.423        4.245       100.0          4.0
2  ARG 5.0Y     103.319        3.918       100.0          5.0
3  ARG 5.5Y      98.204        5.114       100.0          5.5
4  ARG 8.5Y     102.546        4.729       100.0          8.5

In [29]:
writer = pd.ExcelWriter('bond_data.xlsx')
bond_data.to_excel(writer, index = False)
writer.save()

In [30]:
bond_data.to_csv("bond_data.csv", index = False)